version: "3.8"
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:myapp --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME= db
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=2506
      - DATABASE_NAME=fastapiprojectserver
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2506
      POSTGRES_DB: fastapiprojectserver
    ports:
      - "5433:5432"  # Change host port to avoid conflicts
    volumes:
      - pgdata:/var/lib/postgresql/data  # Maps PostgreSQL data directory to a volume

volumes:
  pgdata:
