name: Build and Run Tests for FastAPI Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Step 2: Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up PostgreSQL for testing
      - name: Set up PostgreSQL
        uses: docker://postgres:latest
        env:
          POSTGRES_PASSWORD: 2506
          POSTGRES_USER: postgres
          POSTGRES_DB: fastapiprojectserver_test
        with:
          port: 5432

      # Step 5: Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      # Step 6: Run migrations or create tables if necessary
      - name: Run migrations
        run: |
          # Example command to apply migrations (if you have one)
          alembic upgrade head

      # Step 7: Run pytest tests
      - name: Run pytest tests
        run: |
          export DATABASE_URL=postgresql://postgres:password@localhost:5432/fastapiprojectserver_test
          pytest --maxfail=1 --disable-warnings -q
